#services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=courses'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - '3306'

#Na dependência do docker compose para spring ele usa esses parâmetros hard coded

#Usando configurações manuais:

#services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - '3306'